### PR TITLE
Update SnapshotWriter.cs

### PR DESCRIPTION
**Pull request by gusmanb**
Modified to work with Mono

### CODE REVIEW

**Comment by jvandertil** [comment]
Does this still require the fix included in PR #56? Because both changes are now merged.

**Comment by gusmanb** [comment]
Yes, it does, the patch fixes the problems with nuget executable name
capitalization.

Cheers.

**Comment by jvandertil** [comment]
I meant this commit actually: https://github.com/jvandertil/foundationdb-dotnet-client/commit/6424d7dca12ce87ac6fa4253856b545748a8cd4c

**Comment by gusmanb** [comment]
Hi.

Nope, did'nt noticed that commit, I have created a pull request removing it
and also have standarized conditional mono compilation symbol definition to
the standard one.

Cheers.

2015-03-09 9:08 GMT+01:00 Jos van der Til <notifications@github.com>:

**Pull request merged**
