### PR TITLE
Fix build script for use on Mono

### LINKED ISSUE #35: Build in mono is broken
I have the latest xamarin mono package installed on ubuntu 14.04. When compiling the solution with build.fsx, the error at the bottom is produced.

I have set up a vagrant vmware vm at git@github.com:thinktainer/monobox.git you can use for running the build in mono.
I have added a build.sh on my branch in order to be able to kick off FAKE on linux, you can pull this from here: https://github.com/thinktainer/foundationdb-dotnet-client/tree/mono. Let me know if you need any more information.

	Project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj" (Build target(s)):
		Target RestorePackages:
			Executing: mono --runtime=v4.0.30319 ../.nuget/NuGet.exe install "packages.config" -source ""  -RequireConsent -solutionDir "../ "
			Restoring NuGet packages...
			To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
		Target PrepareForBuild:
			Configuration: Debug Platform: AnyCPU
			Created directory "/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/"
		Target ResolveProjectReferences:
			Project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/FoundationDB.Client.csproj" (default target(s)):
				Target PrepareForBuild:
					Configuration: Debug Platform: x64
				Target GenerateSatelliteAssemblies:
				No input files were specified for target GenerateSatelliteAssemblies, skipping.
				Target GenerateTargetFrameworkMonikerAttribute:
				Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
				Target CoreCompile:
				Skipping target "CoreCompile" because its outputs are up-to-date.
				Target DeployOutputFiles:
					Copying file from '/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/obj/x64/Debug/FoundationDB.Client.dll.mdb' to '/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/FoundationDB.Client.dll.mdb'
					Copying file from '/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/obj/x64/Debug/FoundationDB.Client.dll' to '/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/FoundationDB.Client.dll'
			Done building project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/FoundationDB.Client.csproj".
		Target CopyFilesMarkedCopyLocal:
			Copying file from '/home/vagrant/lib/foundationdb-dotnet-client/packages/Microsoft.Bcl.Immutable.1.1.22-beta/lib/portable-net45+win8+wpa81/System.Collections.Immutable.dll' to '/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/System.Collections.Immutable.dll'
		Target GenerateSatelliteAssemblies:
		No input files were specified for target GenerateSatelliteAssemblies, skipping.
		Target GenerateTargetFrameworkMonikerAttribute:
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
		Target CoreCompile:
			Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /keyfile:FoundationDB.Storage.Memory.snk /optimize- /out:obj/Debug/FoundationDB.Storage.Memory.dll API/LevelWriter.cs API/MemorySnapshotOptions.cs IO/SnapshotFormat.cs IO/SnapshotWriter.cs IO/SnapshotReader.cs IO/Win32MemoryMappedFile.cs IO/Win32SnapshotFile.cs Core/Value.cs API/MemoryClusterHandler.cs Core/Key.cs Core/Memory/ValueHeap.cs Core/Memory/KeyHeap.cs Core/SequenceComparer.cs Core/NativeKeyComparer.cs Core/TransactionWindow.cs Core/Entry.cs Core/Memory/EntryPage.cs Core/Memory/ElasticHeap`1.cs API/MemoryDatabaseHandler.cs API/MemoryDatabase.cs API/MemoryTransactionHandler.cs Collections/ColaOrderedDictionary.cs Collections/ColaRangeDictionary.cs Collections/ColaRangeSet.cs Collections/ColaStore`1.cs Collections/ColaStore.cs Collections/ColaOrderedSet.cs Utils/UnamangedSliceReader.cs Utils/TaskHelpers.cs Utils/UnmanagedHelpers.cs Utils/UnmanagedSliceBuilderPool.cs Utils/USliceComparer.cs Utils/USlice.cs Utils/UnmanagedSliceStream.cs Utils/UnmanagedMemoryHeap.cs Properties/AssemblyInfo.cs Utils/UnmanagedSliceBuilder.cs Properties/VersionInfo.cs /target:library /unsafe+ /define:"DEBUG;TRACE" /nostdlib /reference:/usr/lib/mono/4.5/System.dll /reference:../packages/Microsoft.Bcl.Immutable.1.1.22-beta/lib/portable-net45+win8+wpa81/System.Collections.Immutable.dll /reference:/usr/lib/mono/4.5/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5/System.Core.dll /reference:/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory//FoundationDB.Client.dll /reference:/usr/lib/mono/4.5/mscorlib.dll /reference:/usr/lib/mono/4.5/Facades/System.Collections.Concurrent.dll /reference:/usr/lib/mono/4.5/Facades/System.Collections.dll /reference:/usr/lib/mono/4.5/Facades/System.ComponentModel.Annotations.dll /reference:/usr/lib/mono/4.5/Facades/System.ComponentModel.EventBasedAsync.dll /reference:/usr/lib/mono/4.5/Facades/System.ComponentModel.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Contracts.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Debug.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Tools.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Tracing.dll /reference:/usr/lib/mono/4.5/Facades/System.Dynamic.Runtime.dll /reference:/usr/lib/mono/4.5/Facades/System.Globalization.dll /reference:/usr/lib/mono/4.5/Facades/System.IO.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.Expressions.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.Parallel.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.Queryable.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.dll /reference:/usr/lib/mono/4.5/Facades/System.Net.NetworkInformation.dll /reference:/usr/lib/mono/4.5/Facades/System.Net.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.Net.Requests.dll /reference:/usr/lib/mono/4.5/Facades/System.ObjectModel.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Emit.ILGeneration.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Emit.Lightweight.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Emit.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Extensions.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.dll /reference:/usr/lib/mono/4.5/Facades/System.Resources.ResourceManager.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Extensions.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.InteropServices.WindowsRuntime.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.InteropServices.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Numerics.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Serialization.Json.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Serialization.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Serialization.Xml.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.dll /reference:/usr/lib/mono/4.5/Facades/System.Security.Principal.dll /reference:/usr/lib/mono/4.5/Facades/System.ServiceModel.Http.dll /reference:/usr/lib/mono/4.5/Facades/System.ServiceModel.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.ServiceModel.Security.dll /reference:/usr/lib/mono/4.5/Facades/System.Text.Encoding.Extensions.dll /reference:/usr/lib/mono/4.5/Facades/System.Text.Encoding.dll /reference:/usr/lib/mono/4.5/Facades/System.Text.RegularExpressions.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.Tasks.Parallel.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.Tasks.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.Timer.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.dll /reference:/usr/lib/mono/4.5/Facades/System.Xml.ReaderWriter.dll /reference:/usr/lib/mono/4.5/Facades/System.Xml.XDocument.dll /reference:/usr/lib/mono/4.5/Facades/System.Xml.XmlSerializer.dll /warn:4
			Unhandled Exception:
			Mono.CSharp.InternalErrorException: IO/SnapshotWriter.cs(136,3): FoundationDB.Storage.Memory.IO.SnapshotWriter.<WriteLevelAsync>c__async0.MoveNext() ---> Mono.CSharp.InternalErrorException: (1,1): ---> System.NotImplementedException: The requested feature is not implemented.
			at Mono.CSharp.Indirection.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.MemberExpr.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeCast.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Arguments.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.EmitPredefined (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Nullable`1 loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.Emit (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Location loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodGroupExpr.EmitCall (Mono.CSharp.EmitContext ec, Mono.CSharp.Arguments arguments) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.EmitStatement (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StatementExpression.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Unsafe.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.For.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.EmitEmbedded (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer.EmitMoveNext (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodData.Emit (Mono.CSharp.TypeDefinition parent) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodOrOperator.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Class.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ModuleContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinitionStatic.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0
			[ERROR] FATAL UNHANDLED EXCEPTION: Mono.CSharp.InternalErrorException: IO/SnapshotWriter.cs(136,3): FoundationDB.Storage.Memory.IO.SnapshotWriter.<WriteLevelAsync>c__async0.MoveNext() ---> Mono.CSharp.InternalErrorException: (1,1): ---> System.NotImplementedException: The requested feature is not implemented.
			at Mono.CSharp.Indirection.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.MemberExpr.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeCast.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Arguments.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.EmitPredefined (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Nullable`1 loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.Emit (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Location loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodGroupExpr.EmitCall (Mono.CSharp.EmitContext ec, Mono.CSharp.Arguments arguments) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.EmitStatement (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StatementExpression.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Unsafe.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.For.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.EmitEmbedded (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer.EmitMoveNext (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodData.Emit (Mono.CSharp.TypeDefinition parent) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodOrOperator.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Class.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ModuleContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinitionStatic.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0
	/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets: error : Compiler crashed with code: 1.
		Task "Csc" execution -- FAILED
		Done building target "CoreCompile" in project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj".-- FAILED
	Done building project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj".-- FAILED

	Build FAILED.
	Errors:

	/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj (Build) ->
	/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

		/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets: error : Compiler crashed with code: 1.

		0 Warning(s)
		1 Error(s)

	Time Elapsed 00:00:01.9173210
	Running build failed.
	Error:
	Building /home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj failed with exitcode 1.

### PR DESCRIPTION
**Pull request by jvandertil**
Fixes #35 

I've removed the old NuGet package restore in favor of the normal restore that works on all new versions of Visual Studio as well. This does not work properly with Mono.

Most changes are fixes to paths and case sensitivity issues. Only commit 6424d7dca12ce87ac6fa4253856b545748a8cd4c actually modifies code. This fixes the error in #35.

### CODE REVIEW

**Comment by jvandertil** [comment]
I've submitted this, but now I remember that I might have introduced some tab/space stuff. Will check it out and fix it.

**Comment by KrzysFR** [comment]
The EditorConfig plugin is very usefull for the space vs tabs mixup.

**Comment by jvandertil** [comment]
Should be fixed now :)!

**Comment by jvandertil** [comment]
Will run the tests later this evening, did not have the time to do that yet.

**Comment by KrzysFR** [comment]
The last appveyor build seems to have failed on the package restore: https://ci.appveyor.com/project/KrzysFR/foundationdb-dotnet-client/build/0.9.8.135

**Comment by KrzysFR** [comment]
I'm not exactly sure what's the deal with AppVeyor is. I cleared my local folder, ran the build, and it did download fake+nunit and restored the packages succesfully, so LGTM. If it breaks things for AppVeyor, we'll see to it then.

**Comment by jvandertil** [comment]
Ah yes, I removed the MSBuild based package restore. I'm not sure how AppVeyor works, can you let it run the FAKE file or a batch script? Or only the MSBuild task? Otherwise we might need to revert the change that removes the MSBuild based package restore.

**Comment by KrzysFR** [comment]
Looks like I can make it run either CMD or PS before/after build. What's weird is that VS 2013 and 2015 do the package restore on the first build from a clean install, so not exactly sure what is missing...

I'll make appveyor run "build PackageRestore" before the build.

**Comment by KrzysFR** [comment]
lol, the build is currently stuck on this message:
```
Press any key to continue . . . 
```

That's going to be difficult :frowning:

**Comment by jvandertil** [comment]
LOL. Better remove the PAUSE command from the build.bat ;)

**Comment by KrzysFR** [comment]
Success \o/ https://ci.appveyor.com/project/KrzysFR/foundationdb-dotnet-client/build/0.9.9.148

**Pull request merged**
